name: Sync Upstream

# Controls when the action will run. 
on:
  schedule:
    - cron: '*/5 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4    
        with:
          ref: master  
      - name: Fork Sync With Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v2.2
        with:
          # Upstream repository, e.g. => aormsby/Fork-Sync-With-Upstream-action
          upstream_repository: apache/dubbo-samples
          # Branch to sync from, e.g. => main, master, dev
          upstream_branch: master
          # Branch to push to, e.g. => main, master, prod
          target_branch: master
          # Git user credentials for sigining commit (set to "null" for no credential changes)
          git_user: "null"
          # Git email credentials for sigining commit (set to "null" for no credential changes)
          git_email: "null"
